name: flutter_delivery_app
description: A smart delivery app with introduction, language selection, login, and account creation screens.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  flutter_animate: ^4.0.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/promo.png
    - assets/images/egypt_flag.png
    - assets/images/uk_flag.png

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
